name: country_state_city
description: A dart plugin that deals with coutries, cities and states
version: 0.0.3
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  code_builder: ^4.1.0
  dart_style: ^2.2.0
