name: country_state_city
description: A dart plugin that deals with coutries, cities and states
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
   assets:
     - lib/assets/